### ISSUE TITLE
Set up Auth0 authentication for heal-ctmd 

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#136] opened 2019-10-31 14:32 UTC

**Comment by krobasky** [comment] 2019-11-02 13:42
@mbwatson I'm going to assume this ticket is for setting up an auth0 authentication server on heal-ctmd and triage accordingly. Feel free to add a description and re-label to R2 as you deem appropriate.

**Comment by krobasky** [comment] 2019-11-05 22:08
related to #125

**Comment by krobasky** [comment] 2019-12-13 16:20
UNC's Alex Everett has offered to set-up single sign-on via 'incomon'
He says most of the CTSAs are supported, but not all (e.g., Albert Einstein, Rochester...)
https://www.incommon.org/federation/incommon-federation-participants/

@dcarsey I'm adding you to assignees so you can track:
1. with Alex to ensure NIH directors will be able to use NIH credentials (I think so), and
2. with Theresa to see if it's OK for us to use incommon - meaning most TIN members can use existing credentials, but not all.
When you get a confirmation, add a comment; when you have both items confirmed, please close the ticket, since we won't need Auth0.
On the other hand, if either of the two are NOT confirmed, just reassign this to Matt and put it back into to-do.

Thanks!

**Comment by krobasky** [comment] 2020-01-31 20:25
obsolete, SSO with institutional creds is no longer a requirement as of this week.

**Closed by krobasky** 2020-01-31 20:25 UTC
Labels: FY 2021, R1c
