### ISSUE TITLE
Site specific metrics - need to be able to generate this as a report

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#130] opened 2019-10-15 15:19 UTC
In particular, this was requested by Jane Atkinson -- Director of TIN.

**Comment by davidborland** [comment] 2019-11-04 16:13
Do we have any more information on this feature @dcarsey @krobasky ?

**Comment by davidborland** [comment] 2019-11-04 20:12
Duplicate of #133

**Closed by davidborland** 2019-11-04 20:12 UTC
Labels: R1b
