### ISSUE TITLE
Performance tuning of Pipeline

### ISSUE THREAD

**Issue by xu-hao** [RENCI/ctmd#228] opened 2020-05-14 14:36 UTC
Currently, the pipeline is slow because it has a start-up time.
Can it be faster if it has a separate Spark process running in background waiting for job requests instead of restarting Spark process every time we run the pipeline.

**Comment by xu-hao** [comment] 2020-12-08 07:56
This is not the limiting factor right now.

**Comment by luthfib** [comment] 2020-12-14 17:19
Duplicate of https://github.com/RENCI/ctmd/issues/329

**Closed by luthfib** 2020-12-14 17:19 UTC
Labels: FY 2021, duplicate
