### ISSUE TITLE
Show enrollment per site on enrollment rate graph

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#92] opened 2019-08-22 19:24 UTC
Show enrollment per site on enrollment rate graph, in addition to per study. 

The enrollment of a study is the aggregation across all sites.  NOW show the enrollment from each site.

**Comment by dcarsey** [comment] 2019-08-22 20:00
Create an enrollment rate per site graph - - this is something we report to NIH regularly as well as to the sites (to try to create some healthy competition among sites to increase the enrollment rate)

**Comment by davidborland** [comment] 2019-11-04 17:20
Related to #96

**Comment by davidborland** [comment] 2019-11-04 20:30
Duplicate of #96

**Closed by davidborland** 2019-11-04 20:30 UTC
Labels: R2
