### ISSUE TITLE
upload errors caused by lack of resilient date format handling

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#346] opened 2021-01-05 17:00 UTC
This seems to work:

d-mmm-yy 
Date looks like this (when functioning correctly):  24-Sep-20

This is for sure a problem in the study sites template as well as enrollment data.

Should the templates coach people along and give an example of the required date format?

Let Dawn know when these are created and she can test.
After successful testing, Dawn will send new templates to Jackie.
New templates also need to be installed in all of the places on Stage / CTMD / HEAL.  (uploads page AND each tab where they've been changed)

**Comment by mbwatson** [comment] 2021-01-05 17:03
i'm missing something here. @dcarsey you said in Slack that you were able to successfully upload 

```csv
Proposal ID,Principal Investigator,Site Number,Site ID,CTSA ID,Site Name,Date Reg Packet Sent,Date Contract Sent,Date of IRB Submission,Date of IRB Approval,Date of Contract Execution,Last Patient First Visit,Date of Site Activation,First Patient First Visit,Number of Patients Consented,Number of Patients Enrolled,Number of Patients Withdrawn,Number of Patients Expected,Number of Queries,Number of Protocol Deviations
ProposalID,principalInvestigator,siteNumber,siteId,ctsaId,siteName,dateRegPacketSent,dateContractSent,dateIrbSubmission,dateIrbApproval,dateContractExecution,lpfv,dateSiteActivated,fpfv,patientsConsentedCount,patientsEnrolledCount,patientsWithdrawnCount,patientsExpectedCount,queriesCount,protocolDeviationsCount
171,Kishan Parikh,132,2,2,Duke,10/19/2018,10/29/2018,1/7/2019,1/13/2019,1/15/2019,,1/23/2019,2/13/2019,33,29,0,23,58,0
```

which has dates formatted like `dd/mm/yyyy`

**Comment by dcarsey** [comment] 2021-01-05 17:06
@mbwatson Thanks, Matt.  You're right.  I may have misspoken.  During our meeting, Jackie uploaded enrollment data and THAT did not work.

Either way, I think we need to be consistent about the date format for all of the templates, and I think it should be specified in the template.

**Comment by dcarsey** [comment] 2021-01-06 20:08
[https://www.postgresql.org/docs/9.1/datatype-datetime.html#AEN5595](url)

Date formats that should work ^^

**Comment by krobasky** [comment] 2021-01-07 14:57
Template doesn't specify a date format. Please test and be sure that the code can handle multiple date formats, including:
MM/DD/YYYY
MM/DD/YY
<month>-day
etc.

**Comment by krobasky** [comment] 2021-01-07 14:58
Close this ticket after checking that code is handling dates resiliently and that code has been tested locally

**Comment by luthfib** [comment] 2021-01-07 20:37
We could reproduce issue. If issue somehow persists please reopen the ticket with steps on how to reproduce the bug.

**Comment by luthfib** [comment] 2021-01-07 20:37
We were unable to reproduce this issue. If issue still persists, feel free to reopen with steps on how to reproduce it.

**Closed by luthfib** 2021-01-07 20:37 UTC
Labels: 1.51-staging, bug
