### ISSUE TITLE
Check which metrics are calculated and which metrics are not

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#344] opened 2021-01-05 16:39 UTC
Currently we are not sure which metrics are calculated and which ones are not. We need to take not which metrics are calculated and not them in this ticket, and note which ones are not calculated and note them here as well. 

#335

**Comment by luthfib** [comment] 2021-01-06 16:21
1. Protocol Available to FPFV: fpfv
2. Contract approval/execution cycle time: **dateContractExecution  - dateContractSent**
3. IRB approval cycle time (Full Committee Review): **dateIrbApproval - dateIrbSubmission**
4. Site open to accrual to First Patient / First Visit (FPFV): **fpfv** (This seems like it should be calculation, but currently it is not)
5. Site open to accrual to Last Patient / First Visit: **lpfv** (This seems like it should be calculation, but currently it is not)
6. Protocol to FPFV: **fpfv - dateRegPacketSent**
7. Contract execution time: **dateContractExecution - dateContractSent**
8. sIRB Approval time: **dateIrbApproval - dateIrbSubmission**
9. Site open to FPFV: **fpfv - dateSiteActivated**
10. Site open to LPFV: **lpfv - dateSiteActivated**
11. Randomized patients / Consented patients: **Ratio(patientsEnrolledCount, patientsConsentedCount)**
12. Actual vs expected randomized patient ratio: **Ratio(patientsEnrolledCount, patientsExpectedCount)**
13. Ratio of randomized patients that dropout of the study: **Ratio(patientsWithdrawnCount, patientsEnrolledCount)**
14. Major protocol deviations / randomized patient: **Ratio(protocolDeviationsCount, patientsEnrolledCount)**
15. Queries per total data elements: **queriesCount**
16. Percent of consented patients randomized: **Ratio(patientsEnrolledCount, patientsConsentedCount)**
17. Actual to expected randomized patient ratio: **Ratio(patientsEnrolledCount, patientsExpectedCount)**
18. Ratio of randomized patients that dropout of the study: **Ratio(patientsWithdrawnCount, patientsEnrolledCount)**
19. Major Protocol deviations per randomized patients: **Ratio( protocolDeviationsCount, patientsEnrolledCount)**
20. Queries per data elements: **We don't have the field yet to calculate this**

**Comment by krobasky** [comment] 2021-01-06 18:30
related to #95

**Comment by krobasky** [comment] 2021-01-07 15:17
Close this ticket once
1. ensure the labels are correct and consistent with what we know given #95 #335
2. all the metrics are rendered according to the table above (labels and calculations)
3. jackie has confirmed the names and calculations (especially 4., 5.)

**Comment by luthfib** [comment] 2021-01-07 18:17
Question to Jackie:  Should Reg Packet Sent date be used for Final Protocol date ? Yes and change the labels from Reg packet sent date to Final Protocol Date

**Comment by luthfib** [comment] 2021-01-07 20:33
We found that a majority of these metrics are duplicates based on looking at how they are calculated. We are reaching out to Jackie to inquire if they are to be deleted or if we are leaving them as is.

**Comment by krobasky** [comment] 2021-01-08 13:32
@luthfib looking at the table, it appears that only 1 and 4 are duplicates, and maybe that's only because we're misunderstanding how to do 4 - what other metrics are duplicates?

**Comment by luthfib** [comment] 2021-01-08 15:20
Current table of the proposed metrics to replace the current duplicate ones. https://docs.google.com/spreadsheets/d/18NhuOhlDtMfVCk-AAXT1ELw5hl6t2uCu1CJzrcAnCk8/edit#gid=0

**Closed** 2021-01-09 02:46 UTC
Labels: 1.51-staging, 21Q*-D4
