### ISSUE TITLE
Making test harness data look like more like REDCap

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#285] opened 2020-08-18 18:52 UTC
Need to import the data that Ryan created into the dev server
The data is json data, so it looks like data that’s in CTMD, but not like REDCap
But it’d be helpful if it looked like REDCap
Can we figure out a way to use Shruti’s map to map from JSON into original fields
Have a switch on ingest pipeline to read off of this instead of REDCap server
Cooler to create a server that emulates the REDCap server, but that’s for another day
Shruti needs to get pictures from the dev server
REDCap is free and we can install an instance of it on our server
It might be tedious to mimic the way their data is
We only have to do the subset they’re mapping
Data are mapped into postgres server currently
A script that does an insert of the json into the postgres server on the dev server that might be best.  
Quicker first steps?
Lots of transformations happening between db and after the API gets a hold of it
Ryan’s json …. 20 joins and such to get it to what it looks like; would be hard to reverse engineer it so that it looks like our db
Would it be hard to reverse engineer it using Shruti’s map?  
Might be
Putting this off
Have front end read it off the disc
Environment variable that specifies the API URL
Could read it from a different endpoint and pull in different (test) data
Might have to be more, because he only did proposals and we need a LITTLE bit more info than that

**Comment by krobasky** [comment] 2020-12-15 20:19
#262

**Comment by mbwatson** [comment] 2021-03-04 15:52
related to #280

**Comment by rajshruti18** [comment] 2021-03-04 16:18
Duplicate of https://github.com/RENCI/ctmd/issues/279

**Closed by rajshruti18** 2021-03-04 16:18 UTC
Labels: 1.57-staging, FY 2021
